services:
  - type: web
    name: payhero-backend
    env: python
    plan: starter
    repo: <your-github-repo-url>
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
